[package]
name = "day_08"
version = "1.0.0"
description = "Day 8 - Advent of Code 2019"
authors = ["Jan Baudisch <dev@baudisch.xyz>"]
license = "GPL-3.0-or-later"
readme = "../README.md"
edition = "2018"
workspace = ".."

[dependencies]
common = { path = "../common" }
