name: Lint

on: [push, pull_request]

jobs:
  test:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    
    - name: Lint
      run: cargo clippy --all -- --deny clippy::all
